# Generated by Django 4.0.3 on 2022-07-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='precio_normal',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_usuario_registrado',
            field=models.IntegerField(null=True),
        ),
    ]
