# Generated by Django 4.0.3 on 2022-07-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_datos', '0002_rename_precio_productos_precio_normal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
