# Generated by Django 4.0.3 on 2022-07-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_datos', '0003_remove_productos_codigo_remove_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosAgregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio_normal', models.IntegerField(null=True)),
                ('precio_usuario_registrado', models.IntegerField(null=True)),
            ],
        ),
    ]
